#!/bin/bash
###############################################################
#                Unofficial 'Bash strict mode'                #
# http://redsymbol.net/articles/unofficial-bash-strict-mode/  #
###############################################################
set -euo pipefail
IFS=$'\n\t'
###############################################################

/usr/lib/pi-top-os-apt-installer/pi-top-apt-source-manager remove pi-top-os-unstable

#DEBHELPER#
